name: Build and release plugin
on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  docker-service:
    name: Build dockerized services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ${{ matrix.app }}
        uses: docker/build-push-action@v3
        with:
          context: ./
          platforms: linux/amd64
          push: false
          tags: ghcr.io/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  create-release:
    if: ${{ github.event.pusher.name != 'github action' }}
    runs-on: ubuntu-latest
    needs: docker-service
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Create Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          branch: main
          dry_run: false
        if: ${{ github.ref == 'refs/heads/main' }}
